export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILURE = 'AUTH_SIGNIN_FAILURE';

export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';


export const POST_ADD = 'POST_ADD';
export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS';
export const POST_ADD_FAILURE = 'POST_ADD_FAILURE';

export const POST_LIST = 'POST_LIST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAILURE = 'POST_LIST_FAILURE';

export const POST_VIEW = 'POST_VIEW';
export const POST_VIEW_SUCCESS = 'POST_VIEW_SUCCESS';
export const POST_VIEW_FAILURE = 'POST_VIEW_FAILURE';

export const POST_EDIT = 'POST_EDIT';
export const POST_EDIT_SUCCESS = 'POST_ADD_EDIT';
export const POST_EDIT_FAILURE = 'POST_ADD_EDIT';

export const POST_DELETE = 'POST_DELETE';
export const POST_DELETE_SUCCESS = 'POST_ADD_DELETE';
export const POST_DELETE_FAILURE = 'POST_ADD_DELETE';

export const POST_SEARCH = 'POST_SEARCH';
export const POST_SEARCH_SUCCESS = 'POST_SEARCH_SUCCESS';
export const POST_SEARCH_FAILURE = 'POST_SEARCH_FAILURE';

export const COMMENT_CHANGE = 'COMMENT_CHANGE';
export const COMMENT_CHANGE_SUCCESS = 'COMMENT_CHANGE_SUCCESS';
export const COMMENT_CHANGE_FAILURE = 'COMMENT_CHANGE_FAILURE';

export const CHANNEL_ADD = 'CHANNEL_ADD';
export const CHANNEL_ADD_SUCCESS = 'CHANNEL_ADD_SUCCESS';
export const CHANNEL_ADD_FAILURE = 'CHANNEL_ADD_FAILURE';

export const CHANNEL_LIST = 'CHANNEL_LIST';
export const CHANNEL_LIST_SUCCESS = 'CHANNEL_LIST_SUCCESS';
export const CHANNEL_LIST_FAILURE = 'CHANNEL_LIST_FAILURE';

export const CHANNEL_JOIN = 'CHANNEL_JOIN';
export const CHANNEL_JOIN_SUCCESS = 'CHANNEL_JOIN_SUCCESS';
export const CHANNEL_JOIN_FAILURE = 'CHANNEL_JOIN_FAILURE';

export const CHANNEL_CHANGE = 'CHANNEL_CHANGE';
export const CHANNEL_CHANGE_SUCCESS = 'CHANNEL_CHANGE_SUCCESS';
export const CHANNEL_CHANGE_FAILURE = 'CHANNEL_CHANGE_FAILURE';

export const CHANNEL_SEARCH = 'CHANNEL_SEARCH';
export const CHANNEL_SEARCH_SUCCESS = 'CHANNEL_SEARCH_SUCCESS';
export const CHANNEL_SEARCH_FAILURE = 'CHANNEL_SEARCH_FAILURE';

export const MESSAGE_ADD = 'MESSAGE_ADD';
export const MESSAGE_ADD_SUCCESS = 'MESSAGE_ADD_SUCCESS';
export const MESSAGE_ADD_FAILURE = 'MESSAGE_ADD_FAILURE';

export const MESSAGE_LIST = 'MESSAGE_LIST';
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_FAILURE = 'MESSAGE_LIST_FAILURE';

/* RAW ACTION*/
export const AUTH_SOCKET_RECEIVE = 'AUTH_SOCKET_RECEIVE';
export const ROW_MESSAGE_ADD = 'ROW_MESSAGE_ADD';
export const ROW_MESSAGE_RECEIVE = 'ROW_MESSAGE_RECEIVE';
export const ROW_CHANNEL_ADD = 'ROW_CHANNEL_ADD';
export const ROW_CHANNEL_RECEIVE = 'ROW_CHANNEL_RECEIVE';


export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
