/* AUTH */
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAILURE = 'AUTH_SIGNIN_FAILURE';

export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';

/* CHANNEL */
export const CHANNEL_ADD = 'CHANNEL_ADD';
export const CHANNEL_ADD_SUCCESS = 'CHANNEL_ADD_SUCCESS';
export const CHANNEL_ADD_FAILURE = 'CHANNEL_ADD_FAILURE';

export const CHANNEL_LIST = 'CHANNEL_LIST';
export const CHANNEL_LIST_SUCCESS = 'CHANNEL_LIST_SUCCESS';
export const CHANNEL_LIST_FAILURE = 'CHANNEL_LIST_FAILURE';

export const CHANNEL_JOIN = 'CHANNEL_JOIN';
export const CHANNEL_JOIN_SUCCESS = 'CHANNEL_JOIN_SUCCESS';
export const CHANNEL_JOIN_FAILURE = 'CHANNEL_JOIN_FAILURE';

export const CHANNEL_LEAVE = 'CHANNEL_LEAVE';
export const CHANNEL_LEAVE_SUCCESS = 'CHANNEL_LEAVE_SUCCESS';
export const CHANNEL_LEAVE_FAILURE = 'CHANNEL_LEAVE_FAILURE';

export const CHANNEL_INVITE = 'CHANNEL_INVITE';
export const CHANNEL_INVITE_SUCCESS = 'CHANNEL_INVITE_SUCCESS';
export const CHANNEL_INVITE_FAILURE = 'CHANNEL_INVITE_FAILURE';

export const CHANNEL_CHANGE = 'CHANNEL_CHANGE';
export const CHANNEL_CHANGE_SUCCESS = 'CHANNEL_CHANGE_SUCCESS';
export const CHANNEL_CHANGE_FAILURE = 'CHANNEL_CHANGE_FAILURE';

export const CHANNEL_SEARCH = 'CHANNEL_SEARCH';
export const CHANNEL_SEARCH_SUCCESS = 'CHANNEL_SEARCH_SUCCESS';
export const CHANNEL_SEARCH_FAILURE = 'CHANNEL_SEARCH_FAILURE';

/* MESSAGE */
export const MESSAGE_ADD = 'MESSAGE_ADD';
export const MESSAGE_ADD_SUCCESS = 'MESSAGE_ADD_SUCCESS';
export const MESSAGE_ADD_FAILURE = 'MESSAGE_ADD_FAILURE';

export const MESSAGE_LIST = 'MESSAGE_LIST';
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_FAILURE = 'MESSAGE_LIST_FAILURE';

export const MESSAGE_FILTER = 'MESSAGE_FILTER';
export const MESSAGE_FILTER_SUCCESS = 'MESSAGE_FILTER_SUCCESS';
export const MESSAGE_FILTER_FAILURE = 'MESSAGE_FILTER_FAILURE';

export const MESSAGE_SEARCH = 'MESSAGE_SEARCH';
export const MESSAGE_SEARCH_SUCCESS = 'MESSAGE_SEARCH_SUCCESS';
export const MESSAGE_SEARCH_FAILURE = 'MESSAGE_SEARCH_FAILURE';


/* RAW ACTION*/
export const AUTH_SOCKET_RECEIVE = 'AUTH_SOCKET_RECEIVE';
export const ROW_MESSAGE_ADD = 'ROW_MESSAGE_ADD';
export const ROW_MESSAGE_RECEIVE = 'ROW_MESSAGE_RECEIVE';
export const ROW_CHANNEL_ADD = 'ROW_CHANNEL_ADD';
export const ROW_CHANNEL_RECEIVE = 'ROW_CHANNEL_RECEIVE';
export const ROW_PARTICIPANT_RECEIVE = 'ROW_PARTICIPANT_RECEIVE';
export const ROW_SIGNUP_PARTICIPANT_RECEIVE = 'ROW_SIGNUP_PARTICIPANT_RECEIVE';
export const RECEIVE_MESSAGE_DELETE = 'RECEIVE_MESSAGE_DELETE';
export const LASTDATEID_MESSAGE_DELETE = 'LASTDATEID_MESSAGE_DELETE';
export const RESET_MESSAGE_FILTER = 'RESET_MESSAGE_FILTER';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';

/* ENVIRONMENT */
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
